#  Set updated file so remote servers can detect updates and rebuild headless

image: node:16

pipelines:
  branches:
    main:
      - step:
          script:
            - echo "$(date +%Y-%m-%d_%H:%M:%S)" >> WP-UPDATE-REQUEST.txt
            - git add WP-UPDATE-REQUEST.txt
            - git commit -m "WP Update Request"
            - git push
