#  Template NodeJS build

#  This template allows you to validate your NodeJS code.
#  The workflow allows running tests and code linting on the default branch.

image: node:16

pipelines:
  branches:
    main:
      - step:
          script:
            - echo test >> test.txt
            - git add -A
            - git commit -m "version increment [skip ci]"
            - git push
