# Update WP-UPDATE-REQUEST.txt file so remote servers (eg. WP ENGINE / Vercel ) can detect and rebuild/update headless

image: node:16

pipelines:
  branches:
    main:
      - step:
          name: Deploy to Github
          script:
            - git remote add upstream git@github.com:IDJeffL/bitbucket.git
            - git fetch upstream
            - git pull origin main --allow-unrelated-histories
            - git merge upstream/main