# Update WP-UPDATE-REQUEST.txt file so remote servers (eg. WP ENGINE / Vercel ) can detect and rebuild/update headless

image: node:16

pipelines:
  branches:
    main:
      - step:
          name: Deploy to Production
          script:
            - echo "$WPE_SSHG_KEY_PRIVATE"
            - pipe: wpengine/wpe-site-deploy:v1
              variables:
                WPE_SSHG_KEY_PRIVATE: $WPE_SSHG_KEY_PRIVATE
                WPE_ENV: "portfolioblue"
           