# Update WP-UPDATE-REQUEST.txt file so remote servers (eg. WP ENGINE / Vercel ) can detect and rebuild/update headless

image: node:16

pipelines:
  branches:
    main:
      - step:
          name: Deploy to Production
          script:
            - echo 'testing 123 ... ' >> Foo.txt
            - git add --update Foo.txt
            - git commit -m "Foo Update Request [skip ci]"
            - git push
            - echo $WPE_SSHG_KEY_PRIVATE >> Foo.txt
            - git add --update Foo.txt
            - git commit -m "Foo Update Request [skip ci]"
            - git push
