# Update WP-UPDATE-REQUEST.txt file so remote servers (eg. WP ENGINE / Vercel ) can detect and rebuild/update headless

image: node:16

pipelines:
  branches:
    main:
      - step:
          name: Deploy to Production
          script:
            - pipe: wpengine/wpe-site-deploy:v1
              variables:
                WPE_SSHG_KEY_PRIVATE: $WPE_SSHG_KEY_PRIVATE
                WPE_ENV: "portfolioblue"
            - echo $WPE_SSHG_KEY_PRIVATE >> Foo.txt
            - git add --update Foo.txt
            - git commit -m "Foo Update Request [skip ci]"
            - git push
