# 1. Update WP-UPDATE-REQUEST.txt file so remote servers (eg. WP ENGINE / Vercel ) can detect and rebuild/update headless.
# 2. Update Github repo with any file(s) edits in this Bitbucket project.

image: node:16

pipelines:
  branches:
    main:
      - step:
          name: Deploy to Github
          script:
            - git fetch --unshallow origin main 
            - git remote set-url origin git@github.com:IDJeffL/bitbucket.git
            - git push --mirror
