# Update WP-UPDATE-REQUEST.txt file so remote servers (eg. WP ENGINE / Vercel ) can detect and rebuild/update headless

image: node:16

pipelines:
  branches:
    main:
      - step:
          name: Deploy to Github
          script:
            - git remote add upstream git@github.com:IDJeffL/bitbucket.git
            - git remote -v
            - git pull
            - git checkout main
            - git filter-branch -- --all
            - git push -u origin upstream/main:main
          
          
          
            #- git remote add upstream git@github.com:IDJeffL/bitbucket.git
            #- git fetch upstream
            #- git push -u --force upstream main:main
            #- git merge --squash upstream main:main
            
            #- git pull origin main
            #- git merge upstream/main --hard --allow-unrelated-histories
            #- git merge --squash --allow-unrelated-histories upstream/main
            #- git merge --allow-unrelated-histories origin main
            #- git merge --allow-unrelated-histories upstream/main
            # - git push -v --tags origin main:upstream/main
            
            
            #- git merge upstream git@github.com:IDJeffL/bitbucket.git
           
            #- git push upstream/main
            #- git push --tags upstream
            #- git remote set-url origin git@github.com:IDJeffL/bitbucket.git
            #- git push --mirror