#  Set updated file so remote servers can detect updates and rebuild headless

image: node:16

pipelines:
  branches:
    main:
      - step:
          script:
            - echo "$(date +%Y-%m-%d_%H:%M:%S)" >> LAST-UPDATE.txt
            - git add LAST-UPDATE.txt
            - git commit -m "version increment [skip ci]"
            - git push
