# Update WP-UPDATE-REQUEST.txt file so remote servers (eg. WP ENGINE / Vercel ) can detect and rebuild/update headless

image: node:16

pipelines:
  branches:
    main:
      - step:
          script:
            - echo "" >> WP-UPDATE-REQUEST.txt
            - git add --update WP-UPDATE-REQUEST.txt
            - git commit -m "WP Update Request [skip ci]"
            - git push
