#  Template NodeJS build

#  This template allows you to validate your NodeJS code.
#  The workflow allows running tests and code linting on the default branch.

image: node:16

pipelines:
  default:
    - step:
        script:
        - echo "Made a change in build ${BITBUCKET_BUILD_NUMBER}" >> changes.txt
        - git add changes.txt
        - git commit -m "Updating changes.txt with latest build number."
        - git push
    - parallel:
        - step:
            name: Build and Test
            script:
              - npm install
              - npm run build
        - step:
            name: Code linting
            script:
              - npm install eslint
              - npx eslint .

  